### ISSUE TITLE
areas other than Greater Manchester?

### ISSUE THREAD

**Issue by duleise** [marcusyoung/otp-tutorial#2]
hi, great work. thanks for sharing.
is it possible to create a graph or instance for other areas? i guess this will start from .pbf files.
i'm new to this. excuse me if this request is somewhat too naive.

**Comment by marcusyoung** [comment]
Hi @duleise,

Yes you can create a graph for other areas. You can start by downloading the pbf data from geofabrik: http://download.geofabrik.de/. You will need to drill down into the regions and countries. If you select a large pbf file you will need a lot of RAM to be able to build the graph, so keep that in mind and start off small.

For the GTFS data, you can try here: https://transitfeeds.com/

Hope that helps.

**Comment by duleise** [comment]
Thank you, Marcus. I should have read more closely into the tutorial. And the links you provided are helpful.
I am trying to build an OTP instance now. When I run `otp.jar` I got this error.
`Error: Could not find or load main class otp.jar`
I re-downloaded the latest `otp.jar` and it still occurred.
The only thing I know I should check is Java version.
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

```
Any suggestions on this?



And more questions if this error is fixed:
- Do I need to edit `build-config.json` and `router-config.json` accordingly?
- GTFS data provide public transport routing. If I want to build isochrones using other transport, for example, walking only, do I need to use another GTFS file? Or is it included once the OTP instance is successfully built.

Thank you again for your time and sharing this neat tool.

**Comment by marcusyoung** [comment]
That error suggests the path to otp.jar is not correct.

You will need to remove  :
`routingDefaults: {
        driveOnRight: false
    	}`
unless you want drive on left.

Street routing is provided by the OpenStreetMap data. You can only create valid isochrones for public transport modes and/or walking.

**Comment by duleise** [comment]
I think the path to otp.jar is not the problem.
I did the following and it worked.
```
unzip the gtfs files.
routingDefaults: { driveOnRight: true }
```
Not sure which one did the trick. Now I have the Grizzly running like magic. 
And 'walk only' is one of the multiple travel options.
Thank you again for all your work and help.
