### ISSUE TITLE
Applying this tutorial to other regions and modified otp.jar 

### ISSUE THREAD

**Issue by alexandrebarsacq** [marcusyoung/otp-tutorial#4]
Hello Marcus,
First of all thank you for this tutorial ! 
I'd like to apply this technique on other places of the globe and I'm wondering about the impact of your modified otp.jar (In the pdf you say "This has been compiled (...) that includes a **UK Way Property Set**".
Apart from the OSM and GTFS data for the region I want to apply this technique to, do I need to do something similar for this additional data that you compiled directly in otp ? 
Best,
Alexandre

**Comment by marcusyoung** [comment]
@alexandrebarsacq The way property set is specified during graph build within build-config.json. There are three available (UK, Norway, and default (California-based). See the documentation here:

https://github.com/opentripplanner/OpenTripPlanner/blob/dev-1.x/docs/Configuration.md

You can see the settings used by the way property sets in the relevant files located here:

https://github.com/opentripplanner/OpenTripPlanner/tree/dev-1.x/src/main/java/org/opentripplanner/graph_builder/module/osm

If none of these are suitable, you'll need to create a modified one, and you'll need to build OTP from source to use it.

Hope that helps.

**Comment by alexandrebarsacq** [comment]
It helps a lot, thank you for your fast response !
