### ISSUE TITLE
Thanks and a suggestion!

### ISSUE THREAD

**Issue by magnusburton** [marcusyoung/otp-tutorial#5]
Hi Marcus,

Thanks for this great tutorial. It’s helped me a lot and I’ve got my first OTP instance up and running. Thanks!

I’m wondering how one would go about updating the GTFS data (for example daily). I’d like to use the OTP server as the backend for a transit app I’m working on. Currently I’m regularly shutting down the server, fetching the new data, manually rebuilding the graph, and then powering the server back on. This doesn’t seem efficient and requires me to manually do it.

Is there a better way?
Thanks,

**Comment by marcusyoung** [comment]
@magnusburton 

Thanks for the feedback. Glad you've found the tutorial useful.

I think that question has come up a few times on the user or developer Google Groups for OTP. That is probably the best place to ask. Some potentially useful threads:

https://groups.google.com/g/opentripplanner-users/c/BIqqRRH5pbA/m/Hoh2yB2XAQAJ

https://groups.google.com/g/opentripplanner-users/c/tkkyLei6ex8/m/zKvCecpmCQAJ

https://groups.google.com/g/opentripplanner-dev/c/eGZvxUC4VPU/m/_eLmnFvSAgAJ

https://groups.google.com/g/opentripplanner-dev/c/7YUYgWEkfHI/m/Q_eIPHEHBAAJ

Hopefully  they are useful.
