### ISSUE TITLE
Error with otp_get_times()

### ISSUE THREAD

**Issue by kathy-bi** [marcusyoung/otp-tutorial#6]
When including the option "detail=TRUE", I receive the error "Can't subset columns that don't exist. Column `timeZone` doesn't exist." Is there a quick fix or should I use the source code to adjust the function?

**Comment by marcusyoung** [comment]
That function usually works without an error. Can you please provide your code up to and including that function. Also please confirm what version the running OTP instance is. Thank you.

**Comment by kathy-bi** [comment]
Thanks so much for getting back to me so quickly!!! 

I am using the otp.jar file included in the tutorial folder. Following the tutorial, I start an OTP instance from the command line. then in R, I run: 

# Accompanying code for Part 3 of OTP Tutorial

# Install the otpr package
install.packages("otpr")

# Now load the package
library(otpr)

# Call otpConnect() to define a connection called otpcon
otpcon <- otp_connect(timezone = "Europe/London")

# Call otp_get_times to get attributes of an itinerary
otp_get_times(
  otpcon,
  fromPlace = c(53.43329,-2.13357),
  toPlace =   c(53.36274,-2.27293),
  mode = 'BUS', 
  date = '01-19-2021',
  time = '08:00:00', 
  detail=TRUE
)

Please let me know if I need to provide any additional information. Thanks again!!

**Comment by marcusyoung** [comment]
I'm unable to reproduce this error.

`otpcon <- otp_connect(timezone = "Europe/London")` wouldn't work as the parameter used in `otp_connect()` is tz.  

With the otpr package loaded can you run `sessionInfo()` and then provide a screenshot/copy of the returned data.

Thanks

**Comment by kathy-bi** [comment]
You're so right! I cleared my library and then was unable to successfully run otpcon <- otp_connect(timezone = "Europe/London"), but once I used  otpcon <- otp_connect(tz = "Europe/London") and then ran otp_get_times with the detail option, I had no problems. 

I suspect it's because I had both the otpr and opentripplanner packages loaded? 

Thanks so much for your help!!!

**Comment by marcusyoung** [comment]
Potentially, yes. The opentripplanner package was forked from otpr some years ago. They both share an otp_connect() function, but that function now differs between the two packages.

**Comment by kathy-bi** [comment]
Got it, thanks so much for all of your help!!
